# Generated by following instructions at
# https://betterprogramming.pub/a-step-by-step-guide-to-create-homebrew-taps-from-github-repos-f33d3755ba74
# https://medium.com/@mxcl/maintaining-a-homebrew-tap-for-swift-projects-7287ed379324

class Xcodeinstall < Formula
  desc "This is a command-line tool to download and install Apple's Xcode"
  homepage "https://github.com/sebsto/xcodeinstall"
  url "https://github.com/sebsto/xcodeinstall/archive/refs/tags/v0.9.tar.gz"
  sha256 "e3215bacab2c077232f88eb9fb8e4b559fa066aa95b4a6bd3d84ba4ccb78aedc"
  license "Apache-2.0"

  # insert bottle definition here
  bottle do
    root_url "https://github.com/sebsto/xcodeinstall/releases/download/v0.9"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "95c690012af0970dd0b6bcf5708f4a98a7eed37d46e46f7793d48305ad881b6c"
    sha256 cellar: :any_skip_relocation, ventura: "95c690012af0970dd0b6bcf5708f4a98a7eed37d46e46f7793d48305ad881b6c"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "95c690012af0970dd0b6bcf5708f4a98a7eed37d46e46f7793d48305ad881b6c"
    sha256 cellar: :any_skip_relocation, sonoma: "95c690012af0970dd0b6bcf5708f4a98a7eed37d46e46f7793d48305ad881b6c"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "95c690012af0970dd0b6bcf5708f4a98a7eed37d46e46f7793d48305ad881b6c"
    sha256 cellar: :any_skip_relocation, sequoia: "95c690012af0970dd0b6bcf5708f4a98a7eed37d46e46f7793d48305ad881b6c"
  end

  def install
    system "./scripts/build_fat_binary.sh"
    bin.install ".build/apple/Products/Release/xcodeinstall"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/xcodeinstall --version").chomp
  end
end
