# Generated by following instructions at
# https://betterprogramming.pub/a-step-by-step-guide-to-create-homebrew-taps-from-github-repos-f33d3755ba74
# https://medium.com/@mxcl/maintaining-a-homebrew-tap-for-swift-projects-7287ed379324

class Xcodeinstall < Formula
  desc "This is a command-line tool to download and install Apple's Xcode"
  homepage "https://github.com/sebsto/xcodeinstall"
  url "https://github.com/sebsto/xcodeinstall/archive/refs/tags/v0.4.tar.gz"
  sha256 "29f421d8845ec7d77a4471c2bf4af9454e94af10eeaaf209a0020d7fb845cbf6"
  license "Apache-2.0"

  # insert bottle definition here
  bottle do
    root_url "https://github.com/sebsto/xcodeinstall/releases/download/v0.4"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "27297a789fed30633e7aa6adf49a4e59fb7f90b96e9b7868dc4ba181e6d25a9d"
    sha256 cellar: :any_skip_relocation, monterey: "27297a789fed30633e7aa6adf49a4e59fb7f90b96e9b7868dc4ba181e6d25a9d"
  end

  def install
    system "./scripts/build_fat_binary.sh"
    bin.install ".build/apple/Products/Release/xcodeinstall"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/xcodeinstall --version").chomp
  end
end
